In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
import numpy as np
import pandas as pd

In [29]:
wine_df=pd.read_csv("C:/Users/ss727/Desktop/winequality-red.csv", header=0 ,delimiter=";")

In [31]:
wine_df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [33]:
print(wine_df['fixed acidity'])

0        7.4
1        7.8
2        7.8
3       11.2
4        7.4
5        7.4
6        7.9
7        7.3
8        7.8
9        7.5
10       6.7
11       7.5
12       5.6
13       7.8
14       8.9
15       8.9
16       8.5
17       8.1
18       7.4
19       7.9
20       8.9
21       7.6
22       7.9
23       8.5
24       6.9
25       6.3
26       7.6
27       7.9
28       7.1
29       7.8
        ...
1569     6.2
1570     6.4
1571     6.4
1572     7.3
1573     6.0
1574     5.6
1575     7.5
1576     8.0
1577     6.2
1578     6.8
1579     6.2
1580     7.4
1581     6.2
1582     6.1
1583     6.2
1584     6.7
1585     7.2
1586     7.5
1587     5.8
1588     7.2
1589     6.6
1590     6.3
1591     5.4
1592     6.3
1593     6.8
1594     6.2
1595     5.9
1596     6.3
1597     5.9
1598     6.0
Name: fixed acidity, Length: 1599, dtype: float64

In [34]:
print(wine_df['volatile acidity'])

0       0.700
1       0.880
2       0.760
3       0.280
4       0.700
5       0.660
6       0.600
7       0.650
8       0.580
9       0.500
10      0.580
11      0.500
12      0.615
13      0.610
14      0.620
15      0.620
16      0.280
17      0.560
18      0.590
19      0.320
20      0.220
21      0.390
22      0.430
23      0.490
24      0.400
25      0.390
26      0.410
27      0.430
28      0.710
29      0.645
        ...
1569    0.510
1570    0.360
1571    0.380
1572    0.690
1573    0.580
1574    0.310
1575    0.520
1576    0.300
1577    0.700
1578    0.670
1579    0.560
1580    0.350
1581    0.560
1582    0.715
1583    0.460
1584    0.320
1585    0.390
1586    0.310
1587    0.610
1588    0.660
1589    0.725
1590    0.550
1591    0.740
1592    0.510
1593    0.620
1594    0.600
1595    0.550
1596    0.510
1597    0.645
1598    0.310
Name: volatile acidity, Length: 1599, dtype: float64

In [35]:
import seaborn as sns

In [1]:
sns.pairplot(wine_df,diag_kind='kde')

NameError: name 'sns' is not defined

In [38]:
x=wine_df.drop('quality',axis=1)

In [39]:
y=wine_df[['quality']]

In [41]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [48]:
regression_model=LinearRegression()
regression_model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [46]:
wine_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
fixed acidity,1599.0,8.319637,1.741096,4.60000,7.1000,7.90000,9.200000,15.90000
volatile acidity,1599.0,0.527821,0.179060,0.12000,0.3900,0.52000,0.640000,1.58000
citric acid,1599.0,0.270976,0.194801,0.00000,0.0900,0.26000,0.420000,1.00000
residual sugar,1599.0,2.538806,1.409928,0.90000,1.9000,2.20000,2.600000,15.50000
chlorides,1599.0,0.087467,0.047065,0.01200,0.0700,0.07900,0.090000,0.61100
free sulfur dioxide,1599.0,15.874922,10.460157,1.00000,7.0000,14.00000,21.000000,72.00000
total sulfur dioxide,1599.0,46.467792,32.895324,6.00000,22.0000,38.00000,62.000000,289.00000
density,1599.0,0.996747,0.001887,0.99007,0.9956,0.99675,0.997835,1.00369
pH,1599.0,3.311113,0.154386,2.74000,3.2100,3.31000,3.400000,4.01000
sulphates,1599.0,0.658149,0.169507,0.33000,0.5500,0.62000,0.730000,2.00000
alcohol,1599.0,10.422983,1.065668,8.40000,9.5000,10.20000,11.100000,14.90000
quality,1599.0,5.636023,0.807569,3.00000,5.0000,6.00000,6.000000,8.00000

In [49]:
for idx,col_name in enumerate(x_train.columns):
    print("The coefficient for {} is {}".format(col_name,regression_model.coef_[0][idx]))

The coefficient for fixed acidity is 0.04170741217157226
The coefficient for volatile acidity is -1.1666893794530715
The coefficient for citric acid is -0.2565077594462585
The coefficient for residual sugar is 0.017981734429171746
The coefficient for chlorides is -1.7876625455675186
The coefficient for free sulfur dioxide is 0.004928405769090316
The coefficient for total sulfur dioxide is -0.0035518077331124775
The coefficient for density is -35.453247104044124
The coefficient for pH is -0.385018653484011
The coefficient for sulphates is 0.8837159415805133
The coefficient for alcohol is 0.26387894705968756

In [50]:
intercept=regression_model.intercept_
print("The intercept is {}".format(intercept))

The intercept is [39.46111]

In [51]:
regression_model.score(x_test,y_test)

0.34363701984369954

In [56]:
x.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
dtype: object

In [61]:
x.iloc[36]

fixed acidity            7.8000
volatile acidity         0.6000
citric acid              0.1400
residual sugar           2.4000
chlorides                0.0860
free sulfur dioxide      3.0000
total sulfur dioxide    15.0000
density                  0.9975
pH                       3.4200
sulphates                0.6000
alcohol                 10.8000
Name: 36, dtype: float64

In [70]:
y_pred=regression_model.predict(x_test)

In [74]:
print(y_pred, y_test)

[[5.54151742]
 [5.36697527]
 [6.10297524]
 [5.72712056]
 [6.69610178]
 [5.97998404]
 [6.20846066]
 [5.07111397]
 [5.76515849]
 [5.15879411]
 [6.16451966]
 [5.35627105]
 [5.57045997]
 [6.48419672]
 [5.6100852 ]
 [5.35259629]
 [5.94324305]
 [5.42732464]
 [5.62374716]
 [5.41794815]
 [5.75425012]
 [6.16059497]
 [5.3874175 ]
 [6.44167925]
 [5.45411558]
 [6.29678928]
 [6.1110399 ]
 [5.67286098]
 [5.30822914]
 [5.81112765]
 [5.24229045]
 [6.38624118]
 [5.20075297]
 [6.30560771]
 [4.90903447]
 [5.72068416]
 [5.30481025]
 [5.36761373]
 [6.36721308]
 [5.06667062]
 [6.06771405]
 [5.05351381]
 [5.21010334]
 [6.14683962]
 [5.11695656]
 [5.79169173]
 [5.1111706 ]
 [5.25588698]
 [5.1017325 ]
 [6.05297708]
 [5.64412145]
 [5.47151396]
 [6.24048912]
 [4.81769282]
 [5.09341079]
 [5.97228133]
 [6.05855181]
 [5.95297285]
 [5.84399963]
 [5.25587457]
 [6.28429584]
 [5.2120381 ]
 [5.28160232]
 [5.53519489]
 [4.60072178]
 [5.42724463]
 [6.65779568]
 [5.66796566]
 [5.7854608 ]
 [6.44280015]
 [4.90903447]
 [6.36895525]
 [5.66700492]
 [5.76525678]
 [5.40273937]
 [5.2747125 ]
 [6.14246473]
 [5.35421566]
 [5.70218325]
 [5.80938415]
 [6.03894551]
 [5.11832665]
 [4.97941828]
 [5.52223356]
 [5.60805281]
 [5.11349875]
 [5.31483655]
 [6.1030239 ]
 [5.38879731]
 [5.83792946]
 [5.24203403]
 [6.2916936 ]
 [5.05843444]
 [6.22387675]
 [6.11655507]
 [5.32870802]
 [6.30333712]
 [5.44970805]
 [4.80674026]
 [6.25746251]
 [5.47422683]
 [5.42743176]
 [5.32094009]
 [4.95305566]
 [4.83128731]
 [5.34493548]
 [5.78358964]
 [5.42411212]
 [5.97461575]
 [6.48290345]
 [6.51295747]
 [5.45049455]
 [6.18697882]
 [5.46057415]
 [4.98591111]
 [6.6543167 ]
 [5.28585098]
 [4.95044711]
 [5.15989567]
 [5.20407489]
 [4.89097631]
 [6.6137555 ]
 [6.4008848 ]
 [5.03308013]
 [5.34695608]
 [5.55026177]
 [5.90355344]
 [5.1713198 ]
 [6.2121069 ]
 [5.78239832]
 [5.68483275]
 [5.1390698 ]
 [6.28260368]
 [5.02352696]
 [5.89582519]
 [5.90399783]
 [5.10144004]
 [6.54910222]
 [5.28033754]
 [5.4170401 ]
 [5.11129172]
 [5.39189129]
 [5.75825973]
 [5.31562451]
 [6.01675399]
 [6.36986793]
 [5.64443032]
 [4.77385669]
 [5.76494036]
 [5.88145148]
 [5.51073297]
 [6.52373879]
 [5.15384845]
 [5.21959459]
 [6.07046094]
 [6.18883726]
 [6.27755869]
 [6.21705273]
 [5.93350936]
 [5.42028068]
 [6.16281516]
 [5.80881928]
 [5.11429802]
 [5.16262335]
 [6.39306717]
 [5.94833151]
 [5.72916203]
 [5.113554  ]
 [5.24438852]
 [5.95883119]
 [5.17120601]
 [6.02400385]
 [4.99953648]
 [5.07123941]
 [6.37810961]
 [5.34921552]
 [5.42955586]
 [4.96632969]
 [5.43251322]
 [5.32870802]
 [5.67296216]
 [6.238074  ]
 [5.71262307]
 [5.8213033 ]
 [6.38876077]
 [6.73491837]
 [6.3611626 ]
 [5.56819218]
 [5.14979516]
 [4.88984531]
 [5.44193132]
 [5.7194584 ]
 [5.43520486]
 [5.00466013]
 [5.9077763 ]
 [5.27669678]
 [5.67182639]
 [5.56009549]
 [5.5139764 ]
 [5.30561128]
 [6.1831713 ]
 [5.60426852]
 [6.27095085]
 [5.08034015]
 [6.60296112]
 [5.90413891]
 [5.26269526]
 [4.9387312 ]
 [6.30700051]
 [5.75909041]
 [5.70594496]
 [6.05764948]
 [5.32094009]
 [6.2958531 ]
 [5.32242197]
 [5.14410154]
 [5.25046362]
 [5.00518152]
 [5.98574154]
 [5.59381745]
 [5.75001752]
 [5.2861451 ]
 [5.07413767]
 [5.09561065]
 [5.97575974]
 [5.61527992]
 [5.70673128]
 [5.7565463 ]
 [6.58821761]
 [5.7360949 ]
 [5.28833339]
 [5.07310893]
 [6.14760701]
 [6.15827361]
 [5.46239564]
 [5.23654787]
 [6.2261617 ]
 [5.00958396]
 [5.57488367]
 [5.40464148]
 [5.94666474]
 [6.0102237 ]
 [5.83955589]
 [5.45268827]
 [5.72825006]
 [6.62237988]
 [5.84225056]
 [5.34293381]
 [4.87374339]
 [5.39363939]
 [4.99466668]
 [5.15519426]
 [6.58797455]
 [5.75642241]
 [6.30639231]
 [5.05393857]
 [5.22096212]
 [4.83190985]
 [5.30981347]
 [5.95644718]
 [5.93044971]
 [5.49657231]
 [5.60405607]
 [5.41482063]
 [5.45337523]
 [5.76494036]
 [5.61600495]
 [5.14216073]
 [4.9212673 ]
 [6.20687264]
 [5.45760448]
 [5.72088595]
 [5.11439348]
 [6.42595061]
 [4.96446573]
 [5.74465467]
 [4.9710109 ]
 [6.02400385]
 [5.46244748]
 [5.32334782]
 [6.71724703]
 [5.7846393 ]
 [5.63896265]
 [4.98155871]
 [5.12069101]
 [5.93294345]
 [5.63747754]
 [5.85196315]
 [4.81584424]
 [5.69236936]
 [5.72477298]
 [5.94324305]
 [5.59652516]
 [5.2876367 ]
 [6.32614102]
 [6.09352643]
 [4.97503386]
 [6.3522067 ]
 [5.14814367]
 [5.53125768]
 [5.63139486]
 [6.25546439]
 [4.94131738]
 [5.76347733]
 [5.52603664]
 [5.48004578]
 [4.80390807]
 [6.27118051]
 [5.73714948]
 [4.87838352]
 [5.49764833]
 [5.71560424]
 [5.42503189]
 [6.5878975 ]
 [5.49340109]
 [5.72570782]
 [5.03164794]
 [5.12355421]
 [6.19269068]
 [6.2261617 ]
 [5.26893854]
 [5.73959325]
 [6.9537336 ]
 [5.0269971 ]
 [5.27669678]
 [5.26928903]
 [5.07552036]
 [6.59654522]
 [5.78647668]
 [5.52692309]
 [5.98798638]
 [4.91050979]
 [5.13521453]
 [5.55803588]
 [5.42656358]
 [5.15006985]
 [6.08449133]
 [6.2958531 ]
 [5.55160913]
 [5.58688308]
 [5.25373344]
 [5.61328013]
 [5.65293928]
 [5.68722074]
 [5.46236389]
 [6.79743928]
 [6.20615394]
 [5.53904396]
 [5.23590835]
 [5.34500773]
 [6.05764948]
 [6.68876883]
 [5.42183624]
 [6.34870018]
 [5.46989493]
 [5.17925865]
 [6.62168319]
 [6.48419672]
 [5.10144004]
 [4.22921125]
 [4.9777936 ]
 [6.07512617]
 [5.05832424]
 [6.5768194 ]
 [5.54028123]
 [5.18580374]
 [5.40566777]
 [5.22350191]
 [5.90997763]
 [5.23654787]
 [5.50170128]
 [5.56805189]
 [5.29407583]
 [5.564802  ]
 [5.22578109]
 [5.83506517]
 [6.79389201]
 [6.59801224]
 [5.14410154]
 [6.03312455]
 [6.12951424]
 [5.98125919]
 [6.11910885]
 [5.87499124]
 [5.54021958]
 [6.25418301]
 [5.01062758]
 [5.76382474]
 [5.70601424]
 [5.57653085]
 [5.10605454]
 [5.80204036]
 [5.18105495]
 [5.90113721]
 [5.32934512]
 [5.77542332]
 [5.38879731]
 [6.14760701]
 [5.15852767]
 [6.08366528]]       quality
75          5
1283        6
408         6
1281        6
1118        6
1143        6
1215        6
181         5
1186        5
1252        5
1422        6
248         6
1314        6
1406        6
292         6
60          5
870         6
1486        5
1518        5
478         5
669         6
575         6
194         5
1080        6
790         6
1335        6
301         6
1257        6
528         6
1081        7
...       ...
1593        6
133         6
386         6
1355        5
81          5
1129        6
491         7
481         8
1318        6
1170        6
1148        6
527         6
335         7
1272        5
1197        6
375         7
1358        5
361         6
1578        6
607         6
764         6
1367        6
404         5
1489        6
1273        5
1416        5
1567        5
1204        7
12          5
584         7

[400 rows x 1 columns]